conjur:
  account: dev-conjur-account
  appliance-url: https://conjur.dev.my-org.com
  authn-jwt:
    service-id: dev-jwt-service
  secrets:
    my-secret: data/vault/Conjur-Springboot-Dev/secret1/password
    my-secret2: data/vault/Conjur-Springboot-Dev/secret2/password
    my-secret3: data/vault/Conjur-Springboot-Dev/secret3/password