---
#In case the Token Controller did not create a Secret with an API token exists for our ServiceAccount
#You can check this by running: kubectl get secrets -n conjur-cert
apiVersion: v1
kind: Secret
metadata:
  name: conjur-demo-acct-token
  namespace: conjur-cert
  annotations:
    kubernetes.io/service-account.name: conjur-demo-acct
type: kubernetes.io/service-account-token