---
# This will config map will hold our scripts
apiVersion: v1
kind: ConfigMap
metadata:
  name: push-to-file
  namespace: conjur-cert
data:
  entry-point.sh: |
      #!/bin/bash
      sleep 1
      echo "======================"
      echo "Files were injected by sidecar:"
      ls -ltr /opt/secrets/conjur/
      echo "======================"
      echo "printing /opt/secrets/conjur/credentials.yaml"
      cat /opt/secrets/conjur/credentials.properties
      echo "======================"
      echo "printing /opt/secrets/conjur/credentials.properties"
      cat /opt/secrets/conjur/credentials.properties
      echo "======================"
      echo "running /opt/secrets/conjur/messenger"
      chmod +x /opt/secrets/conjur/messenger
      /opt/secrets/conjur/messenger
      sleep infinity
---
# Deployment for Conjur Secrets Provider - push to file mode as sidecar
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: conjur-push-to-file
  name: demo-sidecar-push-to-file
  namespace: conjur-cert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conjur-push-to-file
  template:
    metadata:
      labels:
        app: conjur-push-to-file
      annotations:
        # Secrets Provider configuration
        conjur.org/container-mode: sidecar
        conjur.org/secrets-destination: file
        conjur.org/secrets-refresh-interval: 10s
        conjur.org/secrets-refresh-enabled: "true"
        # yaml format
        conjur.org/conjur-secrets-policy-path.yaml1: data/kubernetes/applications/safe/
        conjur.org/conjur-secrets.yaml1: |
          - secret3: secret3
          - secret7: secret7
        conjur.org/secret-file-path.yaml1: "./credentials.yaml"
        conjur.org/secret-file-format.yaml1: "yaml"
        # template - properties file format
        conjur.org/conjur-secrets-policy-path.template1: data/kubernetes/applications/safe/
        conjur.org/conjur-secrets.template1: |
          - secret3: secret3
          - secret5: secret5
          - secret7: secret7
        conjur.org/secret-file-template.template1: |
            property.safe.secret3={{ secret "secret3" }}
            property.safe.secret5={{ secret "secret5" }}
            property.safe.secret7={{ secret "secret7" }}
        conjur.org/secret-file-path.template1: "./credentials.properties"
        # template - binary file
        conjur.org/conjur-secrets-policy-path.messenger-app: data/kubernetes/applications/safe/
        conjur.org/conjur-secrets.messenger-app: |
          - b64data: messenger
        conjur.org/secret-file-template.messenger-app: |
            {{ secret "b64data" | b64dec }}
        conjur.org/secret-file-path.messenger-app: "./messenger"
        conjur.org/secret-file-format.messenger-app: "template"
    spec:
      serviceAccountName: conjur-demo-acct
      containers:
      # Our demo application
      - name: demo-application
        image: redhat/ubi8:latest
        command: ["/scripts/entry-point.sh"]
        workingDir: /opt/secrets/conjur
        imagePullPolicy: IfNotPresent
        volumeMounts:
        # Path to the file with the secrets 
          - name: conjur-secrets
            mountPath: /opt/secrets/conjur
        # Path to the entrypoint
          - name: scripts
            mountPath: /scripts
      # Sidecar
      - name: conjur-secrets-provider-push-to-file
        image: 'cyberark/secrets-provider-for-k8s:latest'
        imagePullPolicy: IfNotPresent
        env:
        - name: CONJUR_AUTHN_LOGIN
          value: host/data/kubernetes/applications/demo-application-push-to-file
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: conjur-connect
        volumeMounts:
          - name: podinfo
            mountPath: /conjur/podinfo
          - name: conjur-secrets
            mountPath: /conjur/secrets
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
        # This is where the sidecar keeps is authentiction token recieved from Conjur
        - name: conjur-secrets
          emptyDir:
            medium: Memory
        # Volume for entrypoint
        - name: scripts
          configMap:
            name: push-to-file
            defaultMode: 0755