---
# Summon deployment manifest with empty centos application to consume the secrets
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-summon
  name: demo-summon
  namespace: conjur-cert
spec:
  selector:
    matchLabels:
      app: demo-summon
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-summon
    spec:
      serviceAccountName: conjur-demo-acct
      containers:
      # Demo container - summon
      - name: summon-demo-app
        image: docker.io/assafhazan/summon:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: CONJUR_AUTHN_TOKEN_FILE
            value: /run/conjur/access-token
        envFrom:
          - configMapRef:
              name: conjur-connect
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true
      # Conjur Authenticator init container for summon
      initContainers:
      - image: cyberark/conjur-authn-k8s-client:latest
        imagePullPolicy: IfNotPresent
        name: cyberark-authn-k8s-for-summon
        env:
          - name: CONJUR_AUTHN_LOGIN
            value: host/data/kubernetes/applications/demo-application-summon
          - name: CONTAINER_MODE
            value: init
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        envFrom:
          - configMapRef:
              name: conjur-connect
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
      volumes:
      - emptyDir:
          medium: Memory
        name: conjur-access-token
      - name: summon-conf
        configMap:
          name: summon-config
          defaultMode: 0755
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
            path: annotations
        name: podinfo
---