---
# This will config map will hold our secretless configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: secretless-config
  namespace: conjur-cert
data:
  secretless.yml: |
    version: "2"
    services:
      zoo-postgres:
        connector: pg
        listenOn: tcp://0.0.0.0:5432
        credentials:
          host:
            from: conjur
            get: data/kubernetes/applications/safe/postgres-hostname
          port:
            from: conjur
            get: data/kubernetes/applications/safe/postgres-port
          password:
            from: conjur
            get: data/kubernetes/applications/safe/postgres-password
          username:
            from: conjur
            get: data/kubernetes/applications/safe/postgres-username
---
# Secretless deployment manifest with demo app that connects to postgres
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-secretless
  name: demo-secretless
  namespace: conjur-cert
spec:
  selector:
    matchLabels:
      app: demo-secretless
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-secretless
    spec:
      serviceAccountName: conjur-demo-acct
      containers:
      # Secretless container
      - name: secretless-broker
        image: cyberark/secretless-broker:latest
        imagePullPolicy: IfNotPresent
        args: ["-f", "/etc/secretless/secretless.yml"]
        envFrom:
          - configMapRef:
              name: conjur-connect
        env:
          - name: CONJUR_AUTHN_LOGIN
            value: host/data/kubernetes/applications/demo-application-secretless
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: config
            mountPath: /etc/secretless
            readOnly: true
          - name: podinfo
            mountPath: /conjur/podinfo
      # Demo container
      - name: secretless-demo-app
        image: assafhazan/postgres-secretless-demo:latest
        imagePullPolicy: IfNotPresent
      volumes:
        - name: config
          configMap:
            name: secretless-config
        - name: podinfo
          downwardAPI:
            items:
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations