---
- name: Demo variable pulling from Conjur
  hosts: localhost
  gather_facts: True

  tasks:
  - name: display encrypted password
    debug:
      msg: "{{ ansible_password }}"

  - name: echo password
    shell: "echo {{ ansible_password }}"
    no_log: True
