# app.yml
# Load policy into: data/ansible branch
# conjur policy load -b data/ansible -f app.yml

- !group
  id: apps
  owner: !group admins

- !policy
  id: apps/safe
  owner: !group admins
  body:
    - &ansible-secrets
      - !variable db_password
      - !variable api_key
      - !variable ssh_key

    - !permit
      role: !group /data/ansible/apps
      privileges: [ read, execute ]
      resource: *ansible-secrets

- !host
  id: apps/conjur-demo
  owner: !group admins
  annotations:
    authn/api-key: true
    description: "Host identity for Ansible CLI automation workflows"

- !grant
  role: !group apps
  member: !host apps/conjur-demo
