---
name: conjur-demo
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
on:
  push: 
    paths:
      - github-actions/**
jobs:
  fetch-secret-from-conjur:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets using CyberArk Conjur Secret Fetcher
        uses: cyberark/conjur-action@v2.0.5
        with:
          url: ${{ secrets.CONJUR_URL }}
          account: conjur
          authn_id: ${{ secrets.CONJUR_AUTHN_ID }}
          secrets: data/github/apps/safe/secret1|SECRET1;data/github/apps/safe/secret2|SECRET2;data/github/apps/safe/secret3|SECRET3
          certificate: ${{ secrets.CONJUR_PUBLIC_KEY }}
      - name : Print secrets
        shell: bash
        run: |
          echo "Secrets retrieved:"
          echo "SECRET1: $SECRET1"
          echo "$SECRET1" | sed 's/./& /g'
          echo "SECRET2: $SECRET2"
          echo "$SECRET2" | sed 's/./& /g'
          echo "SECRET3: $SECRET3"
          echo "$SECRET3" | sed 's/./& /g'
