---
- name: Demo variable pulling from Conjur
  hosts: localhost
  gather_facts: True
  vars:
    machine:
      password: '{{ ansible_password }}'

  tasks:
  - name: display encrypted password
    debug:
      var: ansible_password

  - name: echo password
    shell: "echo {{ ansible_password }}"
    no_log: True