kind: Secret
apiVersion: v1
metadata:
  name: argocd-secret
type: Opaque
stringData:
  admin.password: $2a$12$hSl5BgSxu2Iy96zlTdFgBuc5nL9v1eQe2Mim1Pz1Jl/UJMv1jv7Xm
  admin.passwordMtime: 2024-06-24T14:13:52IDT
