apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - vault-plugin-cm.yml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - cmp-plugin.yml

patchesStrategicMerge:
  - argocd-repo-server-patch.yml
  - admin-password-patch.yml