---
# Load policy into root branch
# This policy defines a demo organization for testing basic capabilities

# Define Admins, create admins group, create admin01 user
- !group
  id: admins 
  owner: !user admin

- !user
  id: admin01
  owner: !group admins

- !permit
  role: !group admins
  privileges: [read,update,create]
  resource: !policy root

- !grant
  role: !group admins
  members: 
    - !user admin01

# Define data branch
- !policy
  id: data
  owner: !group admins
  
# Define data/ansible branch, create users, hosts, groups, layers, variables
- !policy
  id: data/ansible
  owner: !group admins

# data/ansible/admins group will admin everything under data/ansible branch
- !group
  id: data/ansible/admins
  owner: !group admins

- !permit
  role: !group data/ansible/admins
  privileges: [read,update,create]
  resource: !policy data/ansible

- !permit
  role: !group data/ansible/admins
  privileges: [read,update,create]
  resource: !group data/ansible/admins

- &users
  - !user
    id: ansible-admin01
    owner: !group data/ansible/admins

- !grant
  role: !group data/ansible/admins
  members: *users