---
# Deployment for an application that consumes Conjur secrets using REST API bash script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-conjur-via-rest
  namespace: conjur-jwt
  labels:
    app: jwtsecrets
spec:
  replicas: 1
  selector:
    matchLabels:
      role: demo
      app: jwtsecrets
  template:
    metadata:
      labels:
        role: demo
        app: jwtsecrets
    spec:
      serviceAccountName: conjur-demo-acct
      containers:
      - name: k8s-jwt-app
        image: assafhazan/rest-api-jwt-consumer:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: conjur-connect

