---
# Summon deployment manifest with empty centos application to consume the secrets
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-summon
  name: demo-summon
  namespace: conjur-jwt
spec:
  selector:
    matchLabels:
      app: demo-summon
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-summon
    spec:
      serviceAccountName: conjur-demo-acct
      containers:
      # Demo container - summon
      - name: summon-demo-app
        image: docker.io/assafhazan/summon:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: CONJUR_AUTHN_JWT_SERVICE_ID
            valueFrom:
              configMapKeyRef:
                name: conjur-connect
                key: CONJUR_AUTHENTICATOR_ID
        envFrom:
          - configMapRef:
              name: conjur-connect
      volumes:
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
            path: annotations
        name: podinfo
---