---
# This will config map will hold our summon configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: summon-config
  namespace: conjur-jwt
data:
  secrets.yml: |
    SECRET2: !var kubernetes/applications/safe/secret2
  demo_consumer.sh: |
    #!/bin/sh
    echo "=================="
    echo "SECRET2: $SECRET2"
    echo "=================="
    # Adding the below to keep the container alive
    while true; do sleep 36000; done
---
# Summon deployment manifest with empty centos application to consume the secrets
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-summon
  name: demo-summon
  namespace: conjur-jwt
spec:
  selector:
    matchLabels:
      app: demo-summon
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-summon
    spec:
      serviceAccountName: conjur-demo-acct
      containers:
      # Demo container - summon
      - name: summon-demo-app
        image: docker.io/assafhazan/summon:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: CONJUR_AUTHN_JWT_SERVICE_ID
            valueFrom:
              configMapKeyRef:
                name: conjur-connect
                key: CONJUR_AUTHENTICATOR_ID
        envFrom:
          - configMapRef:
              name: conjur-connect
        volumeMounts:
          - name: summon-conf
            mountPath: /etc/summon/config
          - name: summon-conf
            mountPath: /etc/summon/demo_app
      volumes:
      - name: summon-conf
        configMap:
          name: summon-config
          defaultMode: 0755
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
            path: annotations
        name: podinfo
---