---
# Injecting the secret paths AND the Conjur authentication details
extra_vars:
  conjur_secret_path_db_password: '{{ db_password_path }}'
  conjur_secret_path_api_key: '{{ api_key_path }}'
  conjur_secret_path_ssh_key: '{{ ssh_key_path }}'

env:
  CONJUR_APPLIANCE_URL: '{{ conjur_url }}'
  CONJUR_ACCOUNT: '{{ conjur_account }}'
  CONJUR_AUTHN_LOGIN: '{{ conjur_authn_login }}'
  CONJUR_AUTHN_API_KEY: '{{ conjur_api_key }}'