---
fields:
  - id: db_password
    type: string
    label: DB Password Path
    secret: true
  - id: api_key
    type: string
    label: API Key Path
    secret: true
  - id: ssh_key
    type: string
    label: SSH Key Path
    secret: true
required:
  - db_password
  - api_key
  - ssh_key