conjur.appliance-url=https://<your-tenant>.secretsmgr.cyberark.cloud/api
conjur.account=conjur
conjur.authn-login=host/data/springboot/demo-app-host
conjur.authn-api-key=<your-conjur-api-key>

conjur.secret.one=data/vault/Conjur-Springboot-Dev/secret1/password
conjur.secret.two=data/vault/Conjur-Springboot-Dev/secret2/password
conjur.secret.three=data/vault/Conjur-Springboot-Dev/secret3/password