spring.application.name=demo-app
spring.profiles.active=dev
# Disable the SpringBoot Logo
spring.main.banner-mode=off
# Disable the Whitelabel Error Page
server.error.whitelabel.enabled=false
# Demo error page
server.error.path=/custom-error
# Externalized properties location
spring.config.location=classpath:/,file:./
