# A minimal pipeline that uses the runner's assigned managed identity to authenticate to Conjur

trigger:
- main

pool:
 default

variables:
# Conjur URL
- name: conjur_url
  value: https://conjur-fqdn:443
# Conjur Authenticator ID
- name: CONJUR_AUTHN_ID
  value: devops
# Conjur Tenant ID
- name: conjur_account
  value: conjur
# Conjur FreeStyle Identity
- name: conjur_identity
  value: host%2Fdata%2Fazure%2Fapps%2Fmanaged-identity01
# Conjur variable path
- name: conjur_variable_path
  value: data/azure/apps/safe/secret1

jobs:
  - job: ConjurDemoRestAPIJWT
    steps:
      - script: |
              # Retrieving access token from Azure IDMS
              AZURE_TOKEN=$(curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F' -H Metadata:true -s | awk -F ':' '/access_token/ {print $2}' | awk -F ',' '{print $1}' | tr -d '"')
              # Authenticating to Conjur with Azure Token
              echo "##vso[task.setvariable variable=conjur_token]$(curl --show-error -f -k -s -X POST "${{ variables.conjur_url }}/authn-azure/$CONJUR_AUTHN_ID/${{ variables.conjur_account }}/${{ variables.conjur_identity }}/authenticate" -H 'Content-Type: application/x-www-form-urlencoded' -H "Accept-Encoding: base64" --data-urlencode "jwt=$AZURE_TOKEN")"
        failOnStderr: true
        displayName: Authenticate to Conjur using agent's aquired access token
      - script: |
              # Using Conjur Token from previous step to pull a variable
              CONJUR_VARIABLE_VALUE=$(curl --show-error -f -k -s -H "Authorization: Token token=\"$CONJUR_TOKEN\"" "${{ variables.conjur_url }}/secrets/${{ variables.conjur_account }}/variable/${{ variables.conjur_variable_path }}")
              # Printing the variable value
              if [ $? -eq 0 ]; then
                printf "=================\nVariable Path: %s\n\nVariable value: %s\n=================\n" "${{ variables.conjur_variable_path }}" "$CONJUR_VARIABLE_VALUE"
              fi
        failOnStderr: true
        displayName: Pulling a variable from Conjur using agent's aquired access token

  - job: ConjurDemoExtension
    steps:
      - task: secretBatchRetrievalConnector@1
        displayName: Retrieving a secret from Conjur using a Service Connection
        inputs:
          ConjurService: 'ConjurDemoConnector'
          secretsyml: './secrets.yml'
      - bash: |
          echo "Secrets retrieved:"
          echo "SECRET2: $(SECRET2)"
          echo "$(SECRET2)" | sed 's/./& /g'
        displayName: Printing secret's value
