---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conjur-follower
  namespace: conjur-cert-follower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conjur-follower
  template:
    metadata:
      labels:
        app: conjur-follower
        name: conjur-follower
        role: follower
    spec:
      serviceAccountName: conjur-demo-acct
      volumes:
      - name: seedfile
        emptyDir:
          medium: Memory
      - name: conjur-token
        emptyDir:
          medium: Memory
      initContainers:
      - name: authenticator
        image: cyberark/dap-seedfetcher
        imagePullPolicy: Always
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: FOLLOWER_HOSTNAME
            value: conjur-follower
          - name: SEEDFILE_DIR
            value: /tmp/seedfile
          - name: CONJUR_AUTHN_LOGIN
            valueFrom:
              configMapKeyRef:
                name: follower-cm
                key: CONJUR_AUTHN_LOGIN
        envFrom:
          - configMapRef:
              name: follower-cm
        volumeMounts:
          - name: seedfile
            mountPath: /tmp/seedfile
          - name: conjur-token
            mountPath: /run/conjur
      containers:
      - name: conjur-appliance
        # Update the below with the conjur-appliance image location
        image: mycorp-registry/conjur-appliance:version
        command: ["/tmp/seedfile/start-follower.sh"]
        imagePullPolicy: Always
        env:
          - name: SEEDFILE_DIR
            value: /tmp/seedfile
          - name: CONJUR_AUTHENTICATORS
            valueFrom:
              configMapKeyRef:
                name: follower-cm
                key: CONJUR_AUTHENTICATORS
        ports:
        - containerPort: 443
          name: https
        readinessProbe:
          httpGet:
            path: /health
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
          - name: seedfile
            mountPath: /tmp/seedfile
            readOnly: true