---
# Load policy into root branch
# This policy defines a demo organization for testing basic capabilities

# Define Admins, create admins group, create admin01 user
- !group
  id: admins 
  owner: !user admin

- !user
  id: admin01
  owner: !group admins

- !permit
  role: !group admins
  privileges: [read,update,create]
  resource: !policy root

- !grant
  role: !group admins
  members: 
    - !user admin01

# Define data branch
- !policy
  id: data
  owner: !group admins
  
# Define data/gitlab branch, create users, hosts, groups, layers, variables
- !policy
  id: data/gitlab
  owner: !group admins

# data/gitlab/admins group will admin everything under data/gitlab branch
- !group
  id: data/gitlab/admins
  owner: !group admins

- !permit
  role: !group data/gitlab/admins
  privileges: [read,update,create]
  resource: !policy data/gitlab

- !permit
  role: !group data/gitlab/admins
  privileges: [read,update,create]
  resource: !group data/gitlab/admins

- &users
  - !user
    id: gitlab-admin01
    owner: !group data/gitlab/admins

- !grant
  role: !group data/gitlab/admins
  members: *users