---
# This will config map will hold our secretless configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: secretless-config
  namespace: conjur-secretless-jwt
data:
  secretless.yml: |
    version: "2"
    services:
      zoo-postgres:
        connector: pg
        listenOn: tcp://0.0.0.0:5432
        credentials:
          host:
            from: conjur
            get: kubernetes/applications/safe/postgres-hostname
          port:
            from: conjur
            get: kubernetes/applications/safe/postgres-port
          password:
            from: conjur
            get: kubernetes/applications/safe/postgres-password
          username:
            from: conjur
            get: kubernetes/applications/safe/postgres-username
---
# This will config map will hold our summon configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: conjur-secretless-jwt
data:
  entry_point.sh: |
    #!/bin/sh
    cd /etc/yum.repos.d/
    sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
    yum install postgresql -y
    psql 'postgresql://localhost:5432/vet' << EOSQL
    \conninfo
    select current_user;
    select * from zoo;
    EOSQL
    sleep infinity
  query_database.sh: |
    #!/bin/sh
    psql 'postgresql://localhost:5432/vet' --command='select * from zoo;'
---
# Secretless deployment manifest with empty centos application to connect to the db
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-secretless
  name: demo-secretless
  namespace: conjur-secretless-jwt
spec:
  selector:
    matchLabels:
      app: demo-secretless
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-secretless
    spec:
      serviceAccountName: conjur-demo-acct
      containers:
      # Demo container - centos
      - name: centos-demo-app
        image: centos
        imagePullPolicy: IfNotPresent
        command: ["sh","-c","/scripts/entry_point.sh"]
        volumeMounts:
          - name: application-config
            mountPath: /scripts
      # Secretless container
      - name: secretless-broker
        image: cyberark/secretless-broker:latest
        imagePullPolicy: IfNotPresent
        args: ["-f", "/etc/secretless/secretless.yml"]
        envFrom:
          - configMapRef:
              name: conjur-connect
        volumeMounts:
          - name: config
            mountPath: /etc/secretless
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: secretless-config
      - name: application-config
        configMap:
          name: application-config
          defaultMode: 0755