---
# Load policy into data branch
# This policy give permissions to the vault and conjur safe

# Add the host we have created to the group 
- !grant
  roles:
    - !group argocd/jwt
  members:
    - !host argocd/system:serviceaccount:argocd:argocd-repo-server

# Add the host to vault/Conjur-ArgoCD/delegation/consumers
- !grant
  roles:
    - !group vault/Conjur-ArgoCD/delegation/consumers
  members:
    - !host argocd/system:serviceaccount:argocd:argocd-repo-server