---
apiVersion: v1
kind: ConfigMap
metadata:
  name: summon-config
  namespace: conjur-jwt-cc
data:
  secrets.yml: |
    SECRET2: !var data/vault/Conjur-Kuberentes/secret2/password
---
# Summon deployment manifest with sh application to consume the secrets
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-summon
  name: demo-summon
  namespace: conjur-jwt-cc
spec:
  selector:
    matchLabels:
      app: demo-summon
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-summon
    spec:
      serviceAccountName: conjur-demo-acct
      containers:
      # Demo container - summon
      - name: summon-demo-app
        image: docker.io/assafhazan/summon:proxyfix
        imagePullPolicy: Always
        env:
          - name: CONJUR_AUTHN_JWT_SERVICE_ID
            valueFrom:
              configMapKeyRef:
                name: conjur-connect
                key: CONJUR_AUTHENTICATOR_ID
        envFrom:
          - configMapRef:
              name: conjur-connect
        volumeMounts:
        - name: config-volume
          mountPath: /scripts/secrets.yml
          subPath: secrets.yml
      volumes:
      - name: config-volume
        configMap:
          name: summon-config
          items:
          - key: secrets.yml
            path: secrets.yml
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
            path: annotations
        name: podinfo
---