---
# This will config map will hold our secretless configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: secretless-config
  namespace: conjur-jwt-cc
data:
  secretless.yml: |
    version: "2"
    services:
      zoo-postgres:
        connector: pg
        listenOn: tcp://0.0.0.0:5432
        credentials:
          host:
            from: conjur
            get: data/vault/Conjur-Kuberentes/Database-PostgreSQL-aws-pub-lab-reception/address
          port:
            from: conjur
            get: data/vault/Conjur-Kuberentes/Database-PostgreSQL-aws-pub-lab-reception/Port
          password:
            from: conjur
            get: data/vault/Conjur-Kuberentes/Database-PostgreSQL-aws-pub-lab-reception/password
          username:
            from: conjur
            get: data/vault/Conjur-Kuberentes/Database-PostgreSQL-aws-pub-lab-reception/username
---
# Secretless deployment manifest with demo app that connects to postgres
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-secretless
  name: demo-secretless
  namespace: conjur-jwt-cc
spec:
  selector:
    matchLabels:
      app: demo-secretless
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-secretless
    spec:
      serviceAccountName: conjur-demo-acct
      containers:
      # Secretless container
      - name: secretless-broker
        image: cyberark/secretless-broker:latest
        imagePullPolicy: IfNotPresent
        args: ["-f", "/etc/secretless/secretless.yml"]
        envFrom:
          - configMapRef:
              name: conjur-connect
        volumeMounts:
          - name: config
            mountPath: /etc/secretless
            readOnly: true
      # Demo container
      - name: secretless-demo-app
        image: assafhazan/postgres-secretless-demo:latest
        imagePullPolicy: IfNotPresent
      volumes:
        - name: config
          configMap:
            name: secretless-config