##########################################################################
###			   Conjur Secrets
#########################################################################
PolicyID=ConjurSecret
PolicyName=Conjur Secret
SearchForUsages=No
PolicyType=Regular
ImmediateInterval=1
AllowedSafes=.*

;**************************************
; Common Tasks Parameters
;**************************************
MinValidityPeriod=60
ResetOveridesMinValidity=yes
ResetOveridesTimeFrame=yes
Timeout=30
UnlockIfFail=no

;**************************************
; Retry Handling
;**************************************
MaximumRetries=5
MinDelayBetweenRetries=90

;**************************************
; Plug-in information
;**************************************
XMLFile=yes

;**************************************
; Change Task
;**************************************
AllowManualChange=Yes
PerformPeriodicChange=No
HeadStartInterval=0
FromHour=-1
ToHour=-1
ChangeNotificationPeriod=-1
DaysNotifyPriorExpiration=0
EnforcePasswordPolicyOnManualChange=No

;**************************************
; Verification Task
;**************************************
VFAllowManualVerification=Yes
VFPerformPeriodicVerification=No
VFFromHour=-1
VFToHour=-1

;**************************************
; Notifications settings
;**************************************
NFNotifyPriorExpiration=No
NFNotifyOnPasswordDisable=No
NFNotifyOnVerificationErrors=No
NFNotifyOnPasswordUsed=No
RCFromHour=-1
RCToHour=-1

;**************************************
;Password properties
;**************************************
PasswordLength=1
MinUpperCase=0
MinLowerCase=0
MinDigit=0
MinSpecial=0
;PasswordForbiddenChars=
;PasswordEffectiveLength=		;Optional