---
# Conjur consumer credentials
apiVersion: v1
kind: Secret
metadata:
  name: conjur-creds
  namespace: conjur-external-secrets
stringData:
  hostid: host/data/kubernetes/eso-consumer
  apikey: $API_KEY
---
# Conjur External Secret Store
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: conjur
  namespace: conjur-external-secrets
spec:
  provider:
    conjur:
      # Service URL
      url: $CONJUR_URL
      # [OPTIONAL] base64 encoded string of certificate, can comment out the below if not needed
      caBundle: $ONE_LINER_B64_CONJUR_CERTIFICATE
      auth:
        apikey:
          # conjur account
          account: "conjur"
          userRef: # Get this from K8S secret
            name: conjur-creds
            key: hostid
          apiKeyRef: # Get this from K8S secret
            name: conjur-creds
            key: apikey