---
# Create external secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: conjur
  namespace: conjur-external-secrets
spec:
  refreshInterval: 10s
  secretStoreRef:
    # This name must match the metadata.name in the `SecretStore`
    name: conjur
    kind: SecretStore
  data:
  - secretKey: secret1
    remoteRef:
      key: data/kubernetes/applications/safe/secret1
  - secretKey: secret2
    remoteRef:
      key: data/kubernetes/applications/safe/secret2
  - secretKey: secret3
    remoteRef:
      key: data/kubernetes/applications/safe/secret3
  - secretKey: secret4
    remoteRef:
      key: data/kubernetes/applications/safe/secret4
  - secretKey: secret5
    remoteRef:
      key: data/kubernetes/applications/safe/secret5
  - secretKey: secret6
    remoteRef:
      key: data/kubernetes/applications/safe/secret6
  - secretKey: secret7
    remoteRef:
      key: data/kubernetes/applications/safe/secret7
  - secretKey: secret8
    remoteRef:
      key: data/kubernetes/applications/safe/secret8