#!/bin/bash
#============ Internal ===============
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$SCRIPT_DIR"/.env
#============ Script ===============
BYPASS_CA_CN="$ROOT_CA_CN" "$SCRIPT_DIR"/tools/01-create-root-ca.sh
BYPASS_SERVER_CN="$POSTGRES_CN" BYPASS_SERVER_KEY_FILE_PATH="$POSTGRES_KEY_FILE_PATH" "$SCRIPT_DIR"/tools/02-create-self-signed-certificate.sh
BYPASS_SERVER_KEY_FILE_PATH="$POSTGRES_KEY_FILE_PATH" BYPASS_SUBJECT_ALT_NAMES="$POSTGRES_SUBJECT_ALT_NAMES" "$SCRIPT_DIR"/tools/03-generate-csr.sh
BYPASS_CA_CERTIFICATE_FILE_PATH="$ROOT_CA_CERTIFICATE_PATH" BYPASS_CA_KEY_FILE_PATH="$ROOT_CA_KEY_PATH" BYPASS_SERVER_CERTIFICATE_FILE_PATH="$POSTGRES_CERTIFICATE_FILE_PATH" "$SCRIPT_DIR"/tools/04-sign-csr.sh

